In [2]:

def test():
    print('test() for function')
    return
test()

class demo:
    def test(self):
        print("test() for the class and method")
        return
obj=demo()
obj.test()

test() for function
test() for the class and method


In [5]:

class demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
    
p1=demo1()
print(p1.fact(5))



120


In [4]:


class demo2:
    def accept(self,p1,p2):
        self.p1=p1
        self.p2=p2
        return
    def display(s):
        print("p1=",s.p1)
        print("p2=",s.p2)
        
c1=demo2()
c1.accept(10,20)
c1.display()



p1= 10
p2= 20


In [6]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
        
    def add(self,p1,p2):
        return p1+p2
    
c1=Demo2(10,20)
print(c1.add(100,200))

300


In [7]:
class Person():
    #Contructor
    def __init__(self,name):
        self.name=name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
    
# Derived Class
class Employee(Person):
    def isEmployee(self):
        return True
    
emp=Person("Ank")
print(emp.getName(),emp.isEmployee())

emp1=Employee("Sra")
print(emp1.getName(),emp1.isEmployee())


Ank False
Sra True


In [8]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [9]:

lst=[1,2,3,4]
array=np.array(lst)
array+10
print(array)

[1 2 3 4]


In [10]:

lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)



(4,)
int32


In [11]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)


(2, 3)
(3, 2)


In [12]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)


[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [13]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [14]:

import numpy as np
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:

np.arange(1,100,9)

np.arange(2,20,2)
np.arange(1,25,2)



array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [17]:
np.arange(2,20,2)
np.arange(1,25,2)



array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [18]:
a1=np.array([(1,2,3),(4,5,6)])
print("Slicing Column: ",a1[:,1])

Slicing Column:  [2 5]


In [19]:
a1=np.array([(1,2,3),(4,5,6)])
print("Slicing Last Column: ",a1[:,2])

Slicing Last Column:  [3 6]


In [20]:

a1=np.random.normal(5,1,10)
print(a1)
print("Min Value =",np.min(a1))
print("Max Value =",np.max(a1))
print("Mean Value =",np.mean(a1))
print("Median Value =",np.median(a1))



[3.25800144 6.19234266 5.70715265 4.31280778 6.22500682 4.76289329
 5.16278197 4.89035148 5.18844956 5.5737563 ]
Min Value = 3.2580014414357
Max Value = 6.225006820715082
Mean Value = 5.127354395977416
Median Value = 5.175615763507211
